// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ArtPlumberRenderer} from "./ArtPlumberRenderer.sol";

/// @notice Minimal ERC-721 (solmate-style), kept in this file so the whole
///         project is a single dependency-free paste into Remix. Swap for
///         OpenZeppelin's ERC721 if you prefer.
abstract contract ERC721 {
    event Transfer(address indexed from, address indexed to, uint256 indexed id);
    event Approval(address indexed owner, address indexed spender, uint256 indexed id);
    event ApprovalForAll(address indexed owner, address indexed operator, bool approved);

    string public name;
    string public symbol;

    mapping(uint256 => address) internal _ownerOf;
    mapping(address => uint256) internal _balanceOf;
    mapping(uint256 => address) public getApproved;
    mapping(address => mapping(address => bool)) public isApprovedForAll;

    constructor(string memory _name, string memory _symbol) {
        name = _name;
        symbol = _symbol;
    }

    function tokenURI(uint256 id) public view virtual returns (string memory);

    function ownerOf(uint256 id) public view returns (address owner) {
        require((owner = _ownerOf[id]) != address(0), "NOT_MINTED");
    }

    function balanceOf(address owner) public view returns (uint256) {
        require(owner != address(0), "ZERO_ADDRESS");
        return _balanceOf[owner];
    }

    function approve(address spender, uint256 id) external {
        address owner = _ownerOf[id];
        require(msg.sender == owner || isApprovedForAll[owner][msg.sender], "NOT_AUTHORIZED");
        getApproved[id] = spender;
        emit Approval(owner, spender, id);
    }

    function setApprovalForAll(address operator, bool approved) external {
        isApprovedForAll[msg.sender][operator] = approved;
        emit ApprovalForAll(msg.sender, operator, approved);
    }

    function transferFrom(address from, address to, uint256 id) public {
        require(from == _ownerOf[id], "WRONG_FROM");
        require(to != address(0), "INVALID_RECIPIENT");
        require(
            msg.sender == from || isApprovedForAll[from][msg.sender] || msg.sender == getApproved[id],
            "NOT_AUTHORIZED"
        );
        _balanceOf[from]--;
        _balanceOf[to]++;
        _ownerOf[id] = to;
        delete getApproved[id];
        emit Transfer(from, to, id);
    }

    function safeTransferFrom(address from, address to, uint256 id) external {
        safeTransferFrom(from, to, id, "");
    }

    function safeTransferFrom(address from, address to, uint256 id, bytes memory data) public {
        transferFrom(from, to, id);
        require(
            to.code.length == 0
                || IERC721Receiver(to).onERC721Received(msg.sender, from, id, data)
                    == IERC721Receiver.onERC721Received.selector,
            "UNSAFE_RECIPIENT"
        );
    }

    function supportsInterface(bytes4 interfaceId) external pure returns (bool) {
        return interfaceId == 0x01ffc9a7 // ERC-165
            || interfaceId == 0x80ac58cd // ERC-721
            || interfaceId == 0x5b5e139f; // ERC-721 Metadata
    }

    function _mint(address to, uint256 id) internal {
        require(to != address(0), "INVALID_RECIPIENT");
        require(_ownerOf[id] == address(0), "ALREADY_MINTED");
        _balanceOf[to]++;
        _ownerOf[id] = to;
        emit Transfer(address(0), to, id);
    }
}

interface IERC721Receiver {
    function onERC721Received(address operator, address from, uint256 id, bytes calldata data)
        external
        returns (bytes4);
}

/// @title  Art Plumber
/// @notice Fully on-chain ERC-721 pixel plumber. No IPFS, no base URI:
///         the SVG and metadata are generated by the contract itself.
///
///         THE HUNT: each token's six gear colors (both plunger suckers,
///         both sticks, suit, boots) are rolled from a seed locked at mint
///         time. You can't pick your colors - you mint and see what you
///         pulled. Matching colors between parts are the rare pulls; see
///         ArtPlumberRenderer for the exact odds and which seed nibble
///         determines which part's color.
///
///         OG DISCOUNT: anyone may mint, but wallets that sent an
///         Ethereum mainnet transaction before November 2021 get their
///         first FREE_ALLOWANCE tokens free; everyone else pays
///         MINT_PRICE for every token. A contract can't read mainnet
///         history (least of all from another chain), so the check
///         happens off-chain - nonce > 0 at mainnet block 13527858, the
///         last block before 2021-11-01 00:00 UTC - and is attested with
///         an EIP-712 voucher signed by `signer`. The voucher is bound to
///         one wallet, this chain, and this contract, so it can't be
///         borrowed or replayed elsewhere. Minting without a voucher is
///         not an error: it is simply the full-price path.
///
///         NO WALLET CAP: a wallet may mint as much of MAX_SUPPLY as it
///         wants. MAX_PER_TX bounds a single call so the mint loop can't
///         exceed the block gas limit, not how much anyone may own.
contract ArtPlumber is ERC721 {
    using ArtPlumberRenderer for ArtPlumberRenderer.Traits;

    /// @notice On-chain forever, readable by anyone, shown on the verified
    ///         contract's Read tab. Mint accordingly.
    string public constant DISCLAIMER =
        "Art Plumbers have no intrinsic value and carry no expectation of financial return. "
        "There is no team and there is no roadmap. They are completely useless and exist "
        "for entertainment purposes only.";

    uint256 public constant MAX_SUPPLY = 2000;

    /// @notice Most tokens one mint() call may take. There is NO per-wallet
    ///         cap - a wallet may mint as much of the supply as it likes -
    ///         so this exists purely as a gas guard: minting is a loop, and
    ///         an unbounded quantity would exceed the block gas limit. Want
    ///         more than this? Send another transaction.
    uint256 public constant MAX_PER_TX = 20;

    /// @notice Tokens an OG wallet mints for free before paying. This is the
    ///         only per-wallet limit in the contract.
    uint256 public constant FREE_ALLOWANCE = 2;

    /// @notice Price per paid token, in the chain's native token (ETH).
    ///         Every token a public wallet mints costs this; for an OG
    ///         wallet only those past FREE_ALLOWANCE do.
    uint256 public constant MINT_PRICE = 0.002 ether;

    /// @notice Where withdraw() sends the mint proceeds. Immutable, like
    ///         everything else here: no owner, no rug surface.
    address public immutable payout;

    /// @notice Address whose EIP-712 vouchers grant mint eligibility.
    ///         Immutable: no owner, no rotation - a compromised or lost
    ///         signer key means redeploying.
    address public immutable signer;

    /// @dev Fixed at deploy (chain fork edge case accepted for simplicity).
    bytes32 private immutable DOMAIN_SEPARATOR;

    bytes32 private constant VOUCHER_TYPEHASH = keccak256("MintVoucher(address wallet)");

    /// @dev secp256k1 half curve order: reject high-s signatures (EIP-2)
    ///      so a third party can't republish a malleated voucher.
    uint256 private constant HALF_CURVE_ORDER =
        0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0;

    uint256 public totalSupply;

    /// @notice How many tokens each address has minted. A counter for
    ///         display and analytics only - it gates nothing.
    mapping(address => uint256) public mintedBy;

    /// @notice How much of its FREE_ALLOWANCE each address has used. Kept
    ///         separate from mintedBy so a wallet that paid before it had a
    ///         voucher can still claim its free tokens afterwards.
    mapping(address => uint256) public freeMintedBy;

    /// @notice The mint seed of each token. The seed alone fully determines
    ///         the artwork: nibbles 0-5 index the shared 16-color palette,
    ///         nibble 6 rolls which plungers appear (see
    ///         ArtPlumberRenderer.traitsOf for the slot <-> nibble map).
    mapping(uint256 => bytes32) public seedOf;

    constructor(address signer_, address payout_) ERC721("Art Plumber", "PLMBR") {
        require(signer_ != address(0), "ZERO_SIGNER");
        require(payout_ != address(0), "ZERO_PAYOUT");
        signer = signer_;
        payout = payout_;
        DOMAIN_SEPARATOR = keccak256(
            abi.encode(
                keccak256(
                    "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
                ),
                keccak256(bytes("Art Plumber")),
                keccak256(bytes("1")),
                block.chainid,
                address(this)
            )
        );
    }

    /// @notice The EIP-712 digest `signer` must sign to vouch for `wallet`.
    ///         Domain: {name: "Art Plumber", version: "1", chainId, this
    ///         contract}; message: MintVoucher(address wallet). Standard
    ///         typed-data signing (viem signTypedData / ethers signTypedData)
    ///         produces a matching signature.
    function voucherDigest(address wallet) public view returns (bytes32) {
        return keccak256(
            abi.encodePacked(
                "\x19\x01", DOMAIN_SEPARATOR, keccak256(abi.encode(VOUCHER_TYPEHASH, wallet))
            )
        );
    }

    /// @notice What `wallet` must send to mint `quantity` tokens with
    ///         `signature`. Free tokens are spent first, so the quote falls
    ///         as an OG's allowance is consumed. Call this and pass the
    ///         result as msg.value - mint() requires an exact match.
    function priceFor(address wallet, uint256 quantity, bytes calldata signature)
        external
        view
        returns (uint256)
    {
        return (quantity - _freeAllotment(wallet, quantity, signature)) * MINT_PRICE;
    }

    /// @notice Mint `quantity` tokens (1-MAX_PER_TX). An OG wallet's first
    ///         FREE_ALLOWANCE tokens are free and the rest cost MINT_PRICE
    ///         each; without a valid voucher every token costs MINT_PRICE.
    ///         There is no per-wallet cap: mint as many as you like, up to
    ///         MAX_PER_TX per transaction, until MAX_SUPPLY runs out.
    ///         Every token's seed - and therefore every color and the
    ///         plunger loadout - is fixed here and can never change.
    /// @param  quantity  1-MAX_PER_TX tokens. Only the per-transaction gas
    ///         guard and MAX_SUPPLY bound how much a wallet can mint.
    /// @param  signature 65-byte EIP-712 voucher (r||s||v) for msg.sender,
    ///         signed by `signer`, or empty to mint at full price. Reusable
    ///         by the same wallet until its free allowance is gone; useless
    ///         to anyone else. An invalid voucher doesn't revert - it just
    ///         earns no discount.
    /// @return firstId the first minted id; the batch is firstId..firstId+quantity-1.
    /// @dev    prevrandao + minter + id keeps the roll unpredictable enough
    ///         for a fun hunt; ids differ within a batch so every token
    ///         still rolls its own seed. (On some L2s prevrandao is weak;
    ///         use commit-reveal or VRF if real value rides on the odds.)
    function mint(uint256 quantity, bytes calldata signature)
        external
        payable
        returns (uint256 firstId)
    {
        require(quantity > 0 && quantity <= MAX_PER_TX, "BAD_QUANTITY");
        uint256 freeNow = _freeAllotment(msg.sender, quantity, signature);
        require(msg.value == (quantity - freeNow) * MINT_PRICE, "WRONG_PRICE");
        require(totalSupply + quantity <= MAX_SUPPLY, "SOLD_OUT");
        if (freeNow > 0) freeMintedBy[msg.sender] += freeNow;
        mintedBy[msg.sender] += quantity;
        firstId = totalSupply + 1;
        for (uint256 i = 0; i < quantity; i++) {
            uint256 id = ++totalSupply;
            seedOf[id] = keccak256(abi.encodePacked(block.prevrandao, msg.sender, id));
            _mint(msg.sender, id);
        }
    }

    /// @notice Send the accumulated mint proceeds to `payout`. Callable by
    ///         anyone - the destination is fixed, so there's nothing to
    ///         gain by calling it for someone else.
    function withdraw() external {
        (bool ok,) = payout.call{value: address(this).balance}("");
        require(ok, "WITHDRAW_FAILED");
    }

    /// @dev How many of `quantity` this wallet takes from its free
    ///      allowance. Zero without a valid voucher, or once spent.
    function _freeAllotment(address wallet, uint256 quantity, bytes calldata signature)
        internal
        view
        returns (uint256)
    {
        if (!_isValidVoucher(wallet, signature)) return 0;
        uint256 used = freeMintedBy[wallet];
        if (used >= FREE_ALLOWANCE) return 0;
        uint256 left = FREE_ALLOWANCE - used;
        return quantity < left ? quantity : left;
    }

    function _isValidVoucher(address wallet, bytes calldata signature)
        internal
        view
        returns (bool)
    {
        if (signature.length != 65) return false;
        bytes32 r = bytes32(signature[0:32]);
        bytes32 s = bytes32(signature[32:64]);
        uint8 v = uint8(signature[64]);
        if (uint256(s) > HALF_CURVE_ORDER) return false;
        address recovered = ecrecover(voucherDigest(wallet), v, r, s);
        return recovered != address(0) && recovered == signer;
    }

    /// @notice A token's rolled traits: the six slot colors (palette
    ///         indices) and which plungers are present.
    function traitsOf(uint256 id) public view returns (ArtPlumberRenderer.Traits memory) {
        _requireMinted(id);
        return ArtPlumberRenderer.traitsOf(seedOf[id]);
    }

    /// @notice On-chain readable match flags, so other contracts (games,
    ///         rewards, burns) can verify a hunter's pull trustlessly.
    function matchesOf(uint256 id)
        external
        view
        returns (bool suckers, bool sticks, bool uniform, bool perfect)
    {
        ArtPlumberRenderer.Traits memory t = traitsOf(id);
        suckers = t.suckersMatch();
        sticks = t.sticksMatch();
        uniform = t.uniformMatch();
        perfect = t.perfectPlumber();
    }

    /// @notice Raw SVG markup for a token (handy for previews and dapps).
    function svgOf(uint256 id) external view returns (string memory) {
        return ArtPlumberRenderer.svg(traitsOf(id));
    }

    /// @inheritdoc ERC721
    function tokenURI(uint256 id) public view override returns (string memory) {
        _requireMinted(id);
        return ArtPlumberRenderer.tokenURI(id, seedOf[id]);
    }

    function _requireMinted(uint256 id) internal view {
        require(_ownerOf[id] != address(0), "NOT_MINTED");
    }
}
