// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ArtPlumberRenderer} from "./ArtPlumberRenderer.sol";

/// @notice Minimal ERC-721 (solmate-style), kept in this file so the whole
///         project is a single dependency-free paste into Remix. Swap for
///         OpenZeppelin's ERC721 if you prefer.
abstract contract ERC721 {
    event Transfer(address indexed from, address indexed to, uint256 indexed id);
    event Approval(address indexed owner, address indexed spender, uint256 indexed id);
    event ApprovalForAll(address indexed owner, address indexed operator, bool approved);

    string public name;
    string public symbol;

    mapping(uint256 => address) internal _ownerOf;
    mapping(address => uint256) internal _balanceOf;
    mapping(uint256 => address) public getApproved;
    mapping(address => mapping(address => bool)) public isApprovedForAll;

    constructor(string memory _name, string memory _symbol) {
        name = _name;
        symbol = _symbol;
    }

    function tokenURI(uint256 id) public view virtual returns (string memory);

    function ownerOf(uint256 id) public view returns (address owner) {
        require((owner = _ownerOf[id]) != address(0), "NOT_MINTED");
    }

    function balanceOf(address owner) public view returns (uint256) {
        require(owner != address(0), "ZERO_ADDRESS");
        return _balanceOf[owner];
    }

    function approve(address spender, uint256 id) external {
        address owner = _ownerOf[id];
        require(msg.sender == owner || isApprovedForAll[owner][msg.sender], "NOT_AUTHORIZED");
        getApproved[id] = spender;
        emit Approval(owner, spender, id);
    }

    function setApprovalForAll(address operator, bool approved) external {
        isApprovedForAll[msg.sender][operator] = approved;
        emit ApprovalForAll(msg.sender, operator, approved);
    }

    function transferFrom(address from, address to, uint256 id) public {
        require(from == _ownerOf[id], "WRONG_FROM");
        require(to != address(0), "INVALID_RECIPIENT");
        require(
            msg.sender == from || isApprovedForAll[from][msg.sender] || msg.sender == getApproved[id],
            "NOT_AUTHORIZED"
        );
        _balanceOf[from]--;
        _balanceOf[to]++;
        _ownerOf[id] = to;
        delete getApproved[id];
        emit Transfer(from, to, id);
    }

    function safeTransferFrom(address from, address to, uint256 id) external {
        safeTransferFrom(from, to, id, "");
    }

    function safeTransferFrom(address from, address to, uint256 id, bytes memory data) public {
        transferFrom(from, to, id);
        require(
            to.code.length == 0
                || IERC721Receiver(to).onERC721Received(msg.sender, from, id, data)
                    == IERC721Receiver.onERC721Received.selector,
            "UNSAFE_RECIPIENT"
        );
    }

    function supportsInterface(bytes4 interfaceId) external pure returns (bool) {
        return interfaceId == 0x01ffc9a7 // ERC-165
            || interfaceId == 0x80ac58cd // ERC-721
            || interfaceId == 0x5b5e139f; // ERC-721 Metadata
    }

    function _mint(address to, uint256 id) internal {
        require(to != address(0), "INVALID_RECIPIENT");
        require(_ownerOf[id] == address(0), "ALREADY_MINTED");
        _balanceOf[to]++;
        _ownerOf[id] = to;
        emit Transfer(address(0), to, id);
    }
}

interface IERC721Receiver {
    function onERC721Received(address operator, address from, uint256 id, bytes calldata data)
        external
        returns (bytes4);
}

/// @title  Art Plumber
/// @notice Fully on-chain ERC-721 pixel plumber. No IPFS, no base URI:
///         the SVG and metadata are generated by the contract itself.
///
///         THE HUNT: each token's six gear colors (both plunger suckers,
///         both sticks, suit, boots) are rolled from a seed locked at mint
///         time. You can't pick your colors - you mint and see what you
///         pulled. Matching colors between parts are the rare pulls; see
///         ArtPlumberRenderer for the exact odds and which seed nibble
///         determines which part's color.
///
///         ELIGIBILITY: only wallets that sent an Ethereum mainnet
///         transaction before November 2021 can mint. A contract can't
///         read mainnet history (least of all from another chain), so the
///         check happens off-chain - nonce > 0 at mainnet block 13527858,
///         the last block before 2021-11-01 00:00 UTC - and is attested
///         with an EIP-712 voucher signed by `signer`. The voucher is
///         bound to one wallet, this chain, and this contract, so it
///         can't be borrowed or replayed elsewhere.
contract ArtPlumber is ERC721 {
    using ArtPlumberRenderer for ArtPlumberRenderer.Traits;

    uint256 public constant MAX_SUPPLY = 1024; // adjust before deploying

    /// @notice Max mints per wallet. mint() is inherently one token per
    ///         transaction; this additionally caps the total a single
    ///         address can ever mint. (Determined hunters can still use
    ///         multiple wallets - this is friction, not a wall.)
    uint256 public constant WALLET_LIMIT = 3;

    /// @notice Address whose EIP-712 vouchers grant mint eligibility.
    ///         Immutable: no owner, no rotation - a compromised or lost
    ///         signer key means redeploying.
    address public immutable signer;

    /// @dev Fixed at deploy (chain fork edge case accepted for simplicity).
    bytes32 private immutable DOMAIN_SEPARATOR;

    bytes32 private constant VOUCHER_TYPEHASH = keccak256("MintVoucher(address wallet)");

    /// @dev secp256k1 half curve order: reject high-s signatures (EIP-2)
    ///      so a third party can't republish a malleated voucher.
    uint256 private constant HALF_CURVE_ORDER =
        0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0;

    uint256 public totalSupply;

    /// @notice How many tokens each address has minted.
    mapping(address => uint256) public mintedBy;

    /// @notice The mint seed of each token. The seed alone fully determines
    ///         the artwork: nibbles 0-5 index the shared 16-color palette,
    ///         nibble 6 rolls which plungers appear (see
    ///         ArtPlumberRenderer.traitsOf for the slot <-> nibble map).
    mapping(uint256 => bytes32) public seedOf;

    constructor(address signer_) ERC721("Art Plumber", "PLMBR") {
        require(signer_ != address(0), "ZERO_SIGNER");
        signer = signer_;
        DOMAIN_SEPARATOR = keccak256(
            abi.encode(
                keccak256(
                    "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
                ),
                keccak256(bytes("Art Plumber")),
                keccak256(bytes("1")),
                block.chainid,
                address(this)
            )
        );
    }

    /// @notice The EIP-712 digest `signer` must sign to vouch for `wallet`.
    ///         Domain: {name: "Art Plumber", version: "1", chainId, this
    ///         contract}; message: MintVoucher(address wallet). Standard
    ///         typed-data signing (viem signTypedData / ethers signTypedData)
    ///         produces a matching signature.
    function voucherDigest(address wallet) public view returns (bytes32) {
        return keccak256(
            abi.encodePacked(
                "\x19\x01", DOMAIN_SEPARATOR, keccak256(abi.encode(VOUCHER_TYPEHASH, wallet))
            )
        );
    }

    /// @notice Mint the next token. The seed - and therefore every color
    ///         and the plunger loadout - is fixed here and can never change.
    /// @param  signature 65-byte EIP-712 voucher (r||s||v) for msg.sender,
    ///         signed by `signer`. Reusable by the same wallet until it
    ///         hits WALLET_LIMIT; useless to anyone else.
    /// @dev    prevrandao + minter + id keeps the roll unpredictable enough
    ///         for a fun hunt. (On some L2s prevrandao is weak; use a
    ///         commit-reveal or VRF if real value rides on the odds.)
    function mint(bytes calldata signature) external returns (uint256 id) {
        require(mintedBy[msg.sender] < WALLET_LIMIT, "WALLET_LIMIT");
        require(_isValidVoucher(msg.sender, signature), "NOT_ELIGIBLE");
        mintedBy[msg.sender]++;
        id = ++totalSupply;
        require(id <= MAX_SUPPLY, "SOLD_OUT");
        seedOf[id] = keccak256(abi.encodePacked(block.prevrandao, msg.sender, id));
        _mint(msg.sender, id);
    }

    function _isValidVoucher(address wallet, bytes calldata signature)
        internal
        view
        returns (bool)
    {
        if (signature.length != 65) return false;
        bytes32 r = bytes32(signature[0:32]);
        bytes32 s = bytes32(signature[32:64]);
        uint8 v = uint8(signature[64]);
        if (uint256(s) > HALF_CURVE_ORDER) return false;
        address recovered = ecrecover(voucherDigest(wallet), v, r, s);
        return recovered != address(0) && recovered == signer;
    }

    /// @notice A token's rolled traits: the six slot colors (palette
    ///         indices) and which plungers are present.
    function traitsOf(uint256 id) public view returns (ArtPlumberRenderer.Traits memory) {
        _requireMinted(id);
        return ArtPlumberRenderer.traitsOf(seedOf[id]);
    }

    /// @notice On-chain readable match flags, so other contracts (games,
    ///         rewards, burns) can verify a hunter's pull trustlessly.
    function matchesOf(uint256 id)
        external
        view
        returns (bool suckers, bool sticks, bool uniform, bool perfect)
    {
        ArtPlumberRenderer.Traits memory t = traitsOf(id);
        suckers = t.suckersMatch();
        sticks = t.sticksMatch();
        uniform = t.uniformMatch();
        perfect = t.perfectPlumber();
    }

    /// @notice Raw SVG markup for a token (handy for previews and dapps).
    function svgOf(uint256 id) external view returns (string memory) {
        return ArtPlumberRenderer.svg(traitsOf(id));
    }

    /// @inheritdoc ERC721
    function tokenURI(uint256 id) public view override returns (string memory) {
        _requireMinted(id);
        return ArtPlumberRenderer.tokenURI(id, seedOf[id]);
    }

    function _requireMinted(uint256 id) internal view {
        require(_ownerOf[id] != address(0), "NOT_MINTED");
    }
}
