// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title  ArtPlumberRenderer
/// @notice Fully on-chain SVG + metadata renderer for the Art Plumber pixel
///         character (frog, 24x24 grid, hangs from a plunger, holds a plunger).
///
///         ================= THE COLOR MATCH HUNT =================
///         Six parts of the character are recolorable "color slots".
///         Each slot's color is determined by ONE NIBBLE (4 bits) of the
///         token's mint seed, used as an index into the shared 16-color
///         PALETTE below. Because every slot draws from the SAME palette,
///         two slots can roll the same index -> their colors MATCH.
///
///         On top of that, each PLUNGER is a presence slot: seed nibble 6
///         decides whether a token has both plungers, only the one on his
///         head, only the one in his hand, or none at all.
///
///           slot        seed nibble   what it determines
///           ----------  -----------   -------------------------------------
///           headSucker  nibble 0      color of plunger SUCKER on head (covers ears)
///           heldSucker  nibble 1      color of SUCKER of the held plunger
///           headStick   nibble 2      color of STICK he hangs from
///           heldStick   nibble 3      color of the OTHER STICK (held handle)
///           suit        nibble 4      color of his work suit
///           boots       nibble 5      color of his boots
///           plungers    nibble 6      0-8  = Double Plunger      (9/16)
///                                     9-11 = Head Plunger only   (3/16)
///                                     12-14= Hand Plunger only   (3/16)
///                                     15   = Plungerless         (1/16)
///
///         Matches only count when both parts are on the art:
///           Suckers Match   both suckers shown AND same color   (~3.5%)
///           Sticks Match    both sticks shown AND same color    (~3.5%)
///           Uniform Match   suit == boots                       (1/16)
///           Perfect Plumber Double Plunger + both matches       (~0.22%)
///
///         Skin, face, belt and background are fixed and are NOT part of
///         the hunt. Shading is drawn as translucent overlay pixels owned
///         by each segment, so any slot color keeps the original pixel-art
///         depth and absent plungers leave no stray pixels.
library ArtPlumberRenderer {
    /// @dev The shared hunt palette: 16 colors x 3 bytes (rgb).
    ///      A slot's nibble n colors it PALETTE[n*3 .. n*3+2].
    bytes internal constant PALETTE =
        hex"c0744a" //  0 Clay           (original sucker orange)
        hex"3e3429" //  1 Ash Brown      (original stick brown)
        hex"383982" //  2 Workwear Blue  (original suit blue)
        hex"2e2423" //  3 Coal           (original boot brown-black)
        hex"b3282d" //  4 Fire Red
        hex"e0a422" //  5 Gold
        hex"2e7d4f" //  6 Pine
        hex"1f8a8a" //  7 Teal
        hex"7a3fa8" //  8 Purple
        hex"d1568e" //  9 Pink
        hex"4f8fdd" // 10 Sky
        hex"8a9a5b" // 11 Moss
        hex"e8e4d8" // 12 Bone
        hex"5b3a24" // 13 Walnut
        hex"ff7f11" // 14 Safety Orange
        hex"23233a"; // 15 Midnight

    bytes16 private constant HEX_DIGITS = "0123456789abcdef";

    /// @dev Everything the seed decides for one token: palette indices
    ///      (0-15) for the six color slots + which plungers are present.
    struct Traits {
        uint8 headSucker; // color: plunger sucker on his head
        uint8 heldSucker; // color: sucker of the plunger he is holding
        uint8 headStick; // color: stick he hangs from
        uint8 heldStick; // color: handle of the held plunger
        uint8 suit; // color: work suit
        uint8 boots; // color: boots
        bool headPlunger; // presence: the plunger on his head (stick+sucker)
        bool heldPlunger; // presence: the plunger in his hand (stick+sucker)
    }

    // ---------------------------------------------------------------------
    // SVG template segments, generated by scripts/build_svg.py.
    // Three self-contained segments (body, head plunger, held plunger),
    // each ending with its own shading overlays, so the two plunger
    // segments can be skipped entirely for tokens that rolled them absent.
    // Constants ending in `fill="#` expect a 6-char hex color next.
    // ---------------------------------------------------------------------

    /// @dev Opens the SVG, paints the black background, opens the suit fill.
    string private constant SVG_START =
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" shape-rendering="crispEdges"><rect width="24" height="24" fill="#000000"/><path fill="#';

    /// @dev Opens one path fill; prefixes each optional plunger segment.
    string private constant OPEN = '<path fill="#';

    /// @dev WORK SUIT pixels (torso, arms, legs), then opens the boots fill.
    string private constant SUIT_PX =
        '" d="M9 12h5v1h-5zM7 13h9v1h-9zM6 14h12v2h-12zM6 16h9v1h-9zM6 17h2v1h-2zM8 18h7v2h-7zM8 20h3v1h-3zM12 20h3v1h-3zM8 21h2v1h-2zM12 21h2v1h-2z"/><path fill="#';

    /// @dev BOOTS pixels, then the fixed art that is NOT part of the hunt:
    ///      skin (3 shades), belt, eye + mouth, and the body's translucent
    ///      shading overlays (suit folds, zipper, boot caps).
    string private constant BODY_FIXED_PX =
        '" d="M8 22h2v1h-2zM12 22h2v1h-2zM8 23h3v1h-3zM12 23h3v1h-3z"/><path fill="#58883f" d="M10 6h1v1h-1zM9 7h1v4h-1zM10 11h1v1h-1z"/><path fill="#639847" d="M10 7h3v1h-3zM11 8h2v1h-2zM10 10h3v1h-3zM11 11h1v1h-1zM18 14h1v2h-1zM6 18h2v1h-2z"/><path fill="#6ba34e" d="M12 6h1v1h-1zM13 7h1v1h-1zM13 10h1v1h-1zM12 11h1v1h-1z"/><path fill="#a3663b" d="M10 9h4v1h-4z"/><path fill="#3b2d2d" d="M8 17h7v1h-7z"/><path fill="#000000" d="M10 8h1v1h-1z"/><path fill="#000" opacity=".12" d="M9 12h1v1h-1zM7 13h2v1h-2zM6 14h1v4h-1zM8 15h1v2h-1zM8 18h1v4h-1zM11 19h1v1h-1zM12 20h1v2h-1z"/><path fill="#000" opacity=".28" d="M8 22h2v1h-2zM12 22h2v1h-2z"/><path fill="#000" opacity=".4" d="M11 12h1v5h-1z"/><path fill="#fff" opacity=".04" d="M13 12h1v1h-1zM14 13h2v1h-2zM16 14h2v1h-2zM14 15h1v2h-1zM11 18h1v1h-1zM14 18h1v3h-1zM10 19h1v2h-1zM9 21h1v1h-1zM13 21h1v1h-1z"/>';

    /// @dev HEAD PLUNGER STICK pixels (the stick he hangs from, rows 0-3),
    ///      then opens the head sucker fill.
    string private constant HEAD_STICK_PX = '" d="M11 0h1v4h-1z"/><path fill="#';

    /// @dev HEAD PLUNGER SUCKER pixels (rubber cup on his head, covers the ear bumps) + the head
    ///      plunger's own shading overlays.
    string private constant HEAD_SUCKER_PX =
        '" d="M11 4h1v1h-1zM10 5h3v1h-3zM9 6h5v1h-5z"/><path fill="#000" opacity=".1" d="M10 5h1v1h-1zM9 6h1v1h-1z"/><path fill="#fff" opacity=".08" d="M11 4h1v1h-1zM12 5h1v1h-1zM13 6h1v1h-1z"/>';

    /// @dev HELD PLUNGER STICK pixels (handle in his hand; the gap at rows
    ///      14-15 is where his green hand grips it), then opens the
    ///      held sucker fill.
    string private constant HELD_STICK_PX =
        '" d="M18 11h1v3h-1zM18 16h1v4h-1z"/><path fill="#';

    /// @dev HELD PLUNGER SUCKER pixels + the held plunger's own shading.
    string private constant HELD_SUCKER_PX =
        '" d="M16 8h5v1h-5zM17 9h3v1h-3zM18 10h1v1h-1z"/><path fill="#000" opacity=".1" d="M16 8h1v1h-1zM17 9h1v1h-1z"/><path fill="#000" opacity=".2" d="M18 12h1v2h-1zM18 16h1v2h-1z"/><path fill="#fff" opacity=".08" d="M20 8h1v1h-1zM19 9h1v1h-1zM18 10h1v1h-1z"/>';

    // ---------------------------------------------------------------------
    // Trait derivation - WHAT DETERMINES EACH PART'S COLOR AND PRESENCE
    // ---------------------------------------------------------------------

    /// @notice Derive a token's traits from its mint seed.
    ///         One nibble of the seed per slot; nibble value = palette index.
    function traitsOf(bytes32 seed) internal pure returns (Traits memory t) {
        uint256 s = uint256(seed);
        // Color of the plunger SUCKER on his head  <- seed nibble 0
        t.headSucker = uint8(s & 0xF);
        // Color of the SUCKER of the plunger he is holding <- seed nibble 1
        t.heldSucker = uint8((s >> 4) & 0xF);
        // Color of the plunger STICK he hangs from <- seed nibble 2
        t.headStick = uint8((s >> 8) & 0xF);
        // Color of the OTHER STICK (held plunger's handle) <- seed nibble 3
        t.heldStick = uint8((s >> 12) & 0xF);
        // Color of the SUIT <- seed nibble 4
        t.suit = uint8((s >> 16) & 0xF);
        // Color of the BOOTS <- seed nibble 5
        t.boots = uint8((s >> 20) & 0xF);
        // Which plungers appear <- seed nibble 6
        // 0-8: both | 9-11: head only | 12-14: hand only | 15: none
        uint8 p = uint8((s >> 24) & 0xF);
        t.headPlunger = p <= 11;
        t.heldPlunger = p <= 8 || (p >= 12 && p <= 14);
    }

    // ------------------------- match checks ------------------------------

    /// @notice Both suckers are on the art AND rolled the same color.
    function suckersMatch(Traits memory t) internal pure returns (bool) {
        return t.headPlunger && t.heldPlunger && t.headSucker == t.heldSucker;
    }

    /// @notice Both sticks are on the art AND rolled the same color.
    function sticksMatch(Traits memory t) internal pure returns (bool) {
        return t.headPlunger && t.heldPlunger && t.headStick == t.heldStick;
    }

    /// @notice Suit and boots rolled the same palette color.
    function uniformMatch(Traits memory t) internal pure returns (bool) {
        return t.suit == t.boots;
    }

    /// @notice The grail: double plunger with matching suckers AND matching
    ///         sticks (~1 in 455).
    function perfectPlumber(Traits memory t) internal pure returns (bool) {
        return suckersMatch(t) && sticksMatch(t);
    }

    /// @notice Metadata label for the plunger presence slot.
    function plungersLabel(Traits memory t) internal pure returns (string memory) {
        if (t.headPlunger && t.heldPlunger) return "Double";
        if (t.headPlunger) return "Head Only";
        if (t.heldPlunger) return "Hand Only";
        return "None";
    }

    // --------------------------- rendering -------------------------------

    /// @notice Assemble the full SVG for a token's traits.
    function svg(Traits memory t) internal pure returns (string memory) {
        // body first: COLOR SLOT suit, COLOR SLOT boots, then the fixed art
        bytes memory out = abi.encodePacked(SVG_START, hexColor(t.suit), SUIT_PX);
        out = abi.encodePacked(out, hexColor(t.boots), BODY_FIXED_PX);
        // PRESENCE SLOT: the plunger on his head (stick he hangs from + sucker)
        if (t.headPlunger) {
            out = abi.encodePacked(out, OPEN, hexColor(t.headStick), HEAD_STICK_PX);
            out = abi.encodePacked(out, hexColor(t.headSucker), HEAD_SUCKER_PX);
        }
        // PRESENCE SLOT: the plunger in his hand (handle + sucker)
        if (t.heldPlunger) {
            out = abi.encodePacked(out, OPEN, hexColor(t.heldStick), HELD_STICK_PX);
            out = abi.encodePacked(out, hexColor(t.heldSucker), HELD_SUCKER_PX);
        }
        return string(abi.encodePacked(out, "</svg>"));
    }

    /// @notice Full ERC-721 tokenURI: base64 JSON with base64 SVG image and
    ///         the trait set hunters filter on. Color traits of an absent
    ///         plunger are omitted (they are not on the art).
    function tokenURI(uint256 id, bytes32 seed) internal pure returns (string memory) {
        Traits memory t = traitsOf(seed);
        bytes memory attrs =
            abi.encodePacked('[{"trait_type":"Plungers","value":"', plungersLabel(t), '"}');
        if (t.headPlunger) {
            attrs = abi.encodePacked(
                attrs,
                ',{"trait_type":"Head Plunger Sucker","value":"',
                colorName(t.headSucker),
                '"},{"trait_type":"Head Plunger Stick","value":"',
                colorName(t.headStick),
                '"}'
            );
        }
        if (t.heldPlunger) {
            attrs = abi.encodePacked(
                attrs,
                ',{"trait_type":"Held Plunger Sucker","value":"',
                colorName(t.heldSucker),
                '"},{"trait_type":"Held Plunger Stick","value":"',
                colorName(t.heldStick),
                '"}'
            );
        }
        attrs = abi.encodePacked(
            attrs,
            ',{"trait_type":"Suit","value":"',
            colorName(t.suit),
            '"},{"trait_type":"Boots","value":"',
            colorName(t.boots),
            '"}'
        );
        attrs = abi.encodePacked(
            attrs,
            ',{"trait_type":"Suckers Match","value":"',
            yesNo(suckersMatch(t)),
            '"},{"trait_type":"Sticks Match","value":"',
            yesNo(sticksMatch(t)),
            '"},{"trait_type":"Uniform Match","value":"',
            yesNo(uniformMatch(t)),
            '"}'
        );
        if (perfectPlumber(t)) {
            attrs = abi.encodePacked(attrs, ',{"trait_type":"Perfect Plumber","value":"Yes"}');
        }
        bytes memory json = abi.encodePacked(
            '{"name":"Art Plumber #',
            toString(id),
            '","description":"Fully on-chain pixel frog plumber. Plunger loadout and six gear colors are rolled from the mint seed - hunt for matching suckers, sticks and uniform.","image":"data:image/svg+xml;base64,',
            encode(bytes(svg(t)))
        );
        json = abi.encodePacked(json, '","attributes":', attrs, "]}");
        return string(abi.encodePacked("data:application/json;base64,", encode(json)));
    }

    /// @notice Human-readable name of a palette color, used in metadata.
    function colorName(uint8 i) internal pure returns (string memory) {
        string[16] memory names = [
            "Clay",
            "Ash Brown",
            "Workwear Blue",
            "Coal",
            "Fire Red",
            "Gold",
            "Pine",
            "Teal",
            "Purple",
            "Pink",
            "Sky",
            "Moss",
            "Bone",
            "Walnut",
            "Safety Orange",
            "Midnight"
        ];
        return names[i];
    }

    /// @dev Palette index -> 6-char lowercase hex (no leading #).
    function hexColor(uint8 idx) internal pure returns (string memory) {
        bytes memory o = new bytes(6);
        for (uint256 k; k < 3; ++k) {
            uint8 b = uint8(PALETTE[uint256(idx) * 3 + k]);
            o[k * 2] = HEX_DIGITS[b >> 4];
            o[k * 2 + 1] = HEX_DIGITS[b & 0xF];
        }
        return string(o);
    }

    function yesNo(bool v) private pure returns (string memory) {
        return v ? "Yes" : "No";
    }

    function toString(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "0";
        uint256 tmp = v;
        uint256 digits;
        while (tmp != 0) {
            digits++;
            tmp /= 10;
        }
        bytes memory buf = new bytes(digits);
        while (v != 0) {
            buf[--digits] = bytes1(uint8(48 + (v % 10)));
            v /= 10;
        }
        return string(buf);
    }

    /// @dev Standard base64 encoding (RFC 4648, with padding).
    function encode(bytes memory data) internal pure returns (string memory) {
        if (data.length == 0) return "";
        bytes memory table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        bytes memory result = new bytes(4 * ((data.length + 2) / 3));
        uint256 i;
        uint256 j;
        for (; i + 3 <= data.length; i += 3) {
            uint256 triple =
                (uint256(uint8(data[i])) << 16) | (uint256(uint8(data[i + 1])) << 8) | uint8(data[i + 2]);
            result[j++] = table[(triple >> 18) & 63];
            result[j++] = table[(triple >> 12) & 63];
            result[j++] = table[(triple >> 6) & 63];
            result[j++] = table[triple & 63];
        }
        uint256 rem = data.length - i;
        if (rem == 1) {
            uint256 triple = uint256(uint8(data[i])) << 16;
            result[j++] = table[(triple >> 18) & 63];
            result[j++] = table[(triple >> 12) & 63];
            result[j++] = "=";
            result[j] = "=";
        } else if (rem == 2) {
            uint256 triple = (uint256(uint8(data[i])) << 16) | (uint256(uint8(data[i + 1])) << 8);
            result[j++] = table[(triple >> 18) & 63];
            result[j++] = table[(triple >> 12) & 63];
            result[j++] = table[(triple >> 6) & 63];
            result[j] = "=";
        }
        return string(result);
    }
}
